-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 11:41:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kanclerza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kanclerza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kanclerza` DEFAULT CHARACTER SET utf8 ;
USE `kanclerza` ;

-- -----------------------------------------------------
-- Table `kanclerza`.`Logowanie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanclerza`.`Logowanie` (
  `idUżytkownika` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NOT NULL,
  `Hasło` VARCHAR(45) NOT NULL,
  `Stopień` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUżytkownika`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  UNIQUE INDEX `idUżytkownika_UNIQUE` (`idUżytkownika` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanclerza`.`Klienci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanclerza`.`Klienci` (
  `idKlienta` INT NOT NULL AUTO_INCREMENT,
  `ImięKlienta` VARCHAR(45) NOT NULL,
  `NazwiskoKlienta` VARCHAR(45) NOT NULL,
  `Telefon_Klienta` VARCHAR(45) NULL,
  `Miejscowość` VARCHAR(45) NOT NULL,
  `Ulica` VARCHAR(45) NOT NULL,
  `Nr_lokalu` VARCHAR(10) NOT NULL,
  `Logowanie_idUżytkownika` INT NOT NULL,
  PRIMARY KEY (`idKlienta`, `Logowanie_idUżytkownika`),
  UNIQUE INDEX `idKlienta_UNIQUE` (`idKlienta` ASC),
  UNIQUE INDEX `Logowanie_idUżytkownika_UNIQUE` (`Logowanie_idUżytkownika` ASC),
  CONSTRAINT `fk_Klienci_Logowanie1`
    FOREIGN KEY (`Logowanie_idUżytkownika`)
    REFERENCES `kanclerza`.`Logowanie` (`idUżytkownika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanclerza`.`Dostawcy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanclerza`.`Dostawcy` (
  `idDostawcy` INT NOT NULL AUTO_INCREMENT,
  `ImięDostawcy` VARCHAR(45) NOT NULL,
  `NazwiskoDostawcy` VARCHAR(45) NOT NULL,
  `TelefonDostawcy` VARCHAR(45) NULL,
  `Logowanie_idUżytkownika` INT NOT NULL,
  PRIMARY KEY (`idDostawcy`, `Logowanie_idUżytkownika`),
  INDEX `fk_Dostawcy_Logowanie1_idx` (`Logowanie_idUżytkownika` ASC),
  UNIQUE INDEX `idDostawcy_UNIQUE` (`idDostawcy` ASC),
  UNIQUE INDEX `Logowanie_idUżytkownika_UNIQUE` (`Logowanie_idUżytkownika` ASC),
  CONSTRAINT `fk_Dostawcy_Logowanie1`
    FOREIGN KEY (`Logowanie_idUżytkownika`)
    REFERENCES `kanclerza`.`Logowanie` (`idUżytkownika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanclerza`.`Zamówienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanclerza`.`Zamówienia` (
  `idZamówienia` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(45) NOT NULL,
  `Data_zamówienia` DATETIME NOT NULL,
  `Data_dostawy` DATETIME NOT NULL,
  `Klienci_idKlienta` INT NOT NULL,
  PRIMARY KEY (`idZamówienia`, `Klienci_idKlienta`),
  INDEX `fk_Zamówienia_Klienci_idx` (`Klienci_idKlienta` ASC),
  UNIQUE INDEX `idZamówienia_UNIQUE` (`idZamówienia` ASC),
  CONSTRAINT `fk_Zamówienia_Klienci`
    FOREIGN KEY (`Klienci_idKlienta`)
    REFERENCES `kanclerza`.`Klienci` (`idKlienta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanclerza`.`Alergeny`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanclerza`.`Alergeny` (
  `idAlergenu` INT NOT NULL AUTO_INCREMENT,
  `Laktoza` TINYINT NULL,
  `Gluten` TINYINT NULL,
  `Pszenica` TINYINT NULL,
  `Kofeina` TINYINT NULL,
  `Glutaminian_sodu` TINYINT NULL,
  PRIMARY KEY (`idAlergenu`),
  UNIQUE INDEX `idAlergenu_UNIQUE` (`idAlergenu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanclerza`.`Produkty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanclerza`.`Produkty` (
  `idProduktu` INT NOT NULL AUTO_INCREMENT,
  `NazwaProduktu` VARCHAR(45) NOT NULL,
  `Alergeny_idAlergenu` INT NOT NULL,
  PRIMARY KEY (`idProduktu`, `Alergeny_idAlergenu`),
  UNIQUE INDEX `idProduktu_UNIQUE` (`idProduktu` ASC),
  INDEX `fk_Produkty_Alergeny1_idx` (`Alergeny_idAlergenu` ASC),
  UNIQUE INDEX `NazwaProduktu_UNIQUE` (`NazwaProduktu` ASC),
  CONSTRAINT `fk_Produkty_Alergeny1`
    FOREIGN KEY (`Alergeny_idAlergenu`)
    REFERENCES `kanclerza`.`Alergeny` (`idAlergenu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanclerza`.`Zestawy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanclerza`.`Zestawy` (
  `idZestawu` INT NOT NULL AUTO_INCREMENT,
  `NazwaZestawu` VARCHAR(45) NOT NULL,
  `Składniki` VARCHAR(200) NOT NULL,
  `Alergeny_idAlergenu` INT NOT NULL,
  PRIMARY KEY (`idZestawu`, `Alergeny_idAlergenu`),
  UNIQUE INDEX `idZestawu_UNIQUE` (`idZestawu` ASC),
  INDEX `fk_Zestawy_Alergeny1_idx` (`Alergeny_idAlergenu` ASC),
  UNIQUE INDEX `NazwaZestawu_UNIQUE` (`NazwaZestawu` ASC),
  CONSTRAINT `fk_Zestawy_Alergeny1`
    FOREIGN KEY (`Alergeny_idAlergenu`)
    REFERENCES `kanclerza`.`Alergeny` (`idAlergenu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanclerza`.`Konkretne_zamówienie_produktu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanclerza`.`Konkretne_zamówienie_produktu` (
  `idKonkretne_zamówienie_produktu` INT NOT NULL AUTO_INCREMENT,
  `Ilość_produktu` INT NOT NULL,
  `Zamówienia_idZamówienia` INT NOT NULL,
  `Zamówienia_Klienci_idKlienta` INT NOT NULL,
  `Produkty_idProduktu` INT NOT NULL,
  PRIMARY KEY (`idKonkretne_zamówienie_produktu`, `Zamówienia_idZamówienia`, `Zamówienia_Klienci_idKlienta`, `Produkty_idProduktu`),
  INDEX `fk_Konkretne_zamówienie_Zamówienia1_idx` (`Zamówienia_idZamówienia` ASC, `Zamówienia_Klienci_idKlienta` ASC),
  INDEX `fk_Konkretne_zamówienie_Produkty1_idx` (`Produkty_idProduktu` ASC),
  UNIQUE INDEX `idKonkretne_zamówienie_produktu_UNIQUE` (`idKonkretne_zamówienie_produktu` ASC),
  CONSTRAINT `fk_Konkretne_zamówienie_Zamówienia1`
    FOREIGN KEY (`Zamówienia_idZamówienia` , `Zamówienia_Klienci_idKlienta`)
    REFERENCES `kanclerza`.`Zamówienia` (`idZamówienia` , `Klienci_idKlienta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Konkretne_zamówienie_Produkty1`
    FOREIGN KEY (`Produkty_idProduktu`)
    REFERENCES `kanclerza`.`Produkty` (`idProduktu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanclerza`.`Konkretne_zamówienie_zestawu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanclerza`.`Konkretne_zamówienie_zestawu` (
  `idKonkretne_zamówienie_zestawu` INT NOT NULL AUTO_INCREMENT,
  `Ilość_zestawów` INT NOT NULL,
  `Zamówienia_idZamówienia` INT NOT NULL,
  `Zamówienia_Klienci_idKlienta` INT NOT NULL,
  `Zestawy_idZestawu` INT NOT NULL,
  PRIMARY KEY (`idKonkretne_zamówienie_zestawu`, `Zamówienia_idZamówienia`, `Zamówienia_Klienci_idKlienta`, `Zestawy_idZestawu`),
  INDEX `fk_Konkretne_zamówienie_zestawu_Zamówienia1_idx` (`Zamówienia_idZamówienia` ASC, `Zamówienia_Klienci_idKlienta` ASC),
  INDEX `fk_Konkretne_zamówienie_zestawu_Zestawy1_idx` (`Zestawy_idZestawu` ASC),
  UNIQUE INDEX `idKonkretne_zamówienie_zestawu_UNIQUE` (`idKonkretne_zamówienie_zestawu` ASC),
  CONSTRAINT `fk_Konkretne_zamówienie_zestawu_Zamówienia1`
    FOREIGN KEY (`Zamówienia_idZamówienia` , `Zamówienia_Klienci_idKlienta`)
    REFERENCES `kanclerza`.`Zamówienia` (`idZamówienia` , `Klienci_idKlienta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Konkretne_zamówienie_zestawu_Zestawy1`
    FOREIGN KEY (`Zestawy_idZestawu`)
    REFERENCES `kanclerza`.`Zestawy` (`idZestawu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kanclerza`.`Administratorzy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kanclerza`.`Administratorzy` (
  `idAdministratora` INT NOT NULL AUTO_INCREMENT,
  `ImięAdministratora` VARCHAR(45) NULL,
  `NazwiskoAdministratora` VARCHAR(45) NULL,
  `Logowanie_idUżytkownika` INT NOT NULL,
  PRIMARY KEY (`idAdministratora`, `Logowanie_idUżytkownika`),
  INDEX `fk_Administratorzy_Logowanie1_idx` (`Logowanie_idUżytkownika` ASC),
  UNIQUE INDEX `idAdministratora_UNIQUE` (`idAdministratora` ASC),
  UNIQUE INDEX `Logowanie_idUżytkownika_UNIQUE` (`Logowanie_idUżytkownika` ASC),
  CONSTRAINT `fk_Administratorzy_Logowanie1`
    FOREIGN KEY (`Logowanie_idUżytkownika`)
    REFERENCES `kanclerza`.`Logowanie` (`idUżytkownika`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
